### ISSUE TITLE
Nutrition System poorly documented

### ISSUE THREAD

**Issue by hanmhan** [weinih/eep153project4#5]
Code styled poorly
Vague or no descriptions of functions/blocks
Lots of grammatical errors
No names for graphs

**Comment by meiyinghuang** [comment]
> Code styled poorly
> Vague or no descriptions of functions/blocks
> Lots of grammatical errors
> No names for graphs

Since most of the coding is very similar to the lecture slides, and we followed the same steps to compute the Demand System and Nutrition System and etc. The only few things that we did differently would be the population we chose and the issues that we are trying to solve. Speaking to that, we already had those descriptions written in the post.
